### ISSUE TITLE
Add ACL support

### ISSUE THREAD

**Issue by muzzol** [bugy/script-server#118]
This is a feature request for Advanced Control List on runners.

```
{
    "name": "Visualitza log",
    "script_path": "/opt/scripts/test1.sh",
    "groups": [
        "web-developers",
        "sys-operators"
    ]
} 
```

So only members of those specified groups can see defined scripts.

**Comment by muzzol** [comment]
a really simple example about getting all groups from a user:


```
#!/usr/bin/python3

# variables
LDAP_URI = "ldap://172.19.0.19:389"
LDAP_USER = "uid=u101049,ou=persones,ou=users,dc=consorci,dc=global"
LDAP_PASS = "1234"
LDAP_BASEDN = "dc=global"
LDAP_SEARCH = "(member=uid=u101049,ou=persones,ou=users,dc=consorci,dc=global)"
LDAP_ATT = "cn"

# biblioteques
import ldap

# connexió inicial
l = ldap.initialize(LDAP_URI)
l.simple_bind_s(LDAP_USER, LDAP_PASS)

# cerca
groups = l.search_s(LDAP_BASEDN, ldap.SCOPE_SUBTREE, LDAP_SEARCH, [LDAP_ATT])
print (groups)

```

**Comment by bugy** [comment]
Hi @muzzol, thanks for the feature request :) I was going to implement it for 

Your second comment (regarding ldap) is quite important. Are you using ldap? To be honest I was going to implement own grouping for script server. 
But your idea about getting groups from LDAP (if this authentication is available) is quite cool. However there is a small problem with it: I have access to user password only on user login. I don't store it anywhere (and won't) to avoid even small probability of exposing it. And user login is forced only once a month. So cached groups could be quite obsolete. Do you think it will still be fine?

**Comment by muzzol** [comment]
Yes, I use LDAP to centralize all my user data and I don't think you need the password once you log in.

caching for the whole session is the usual aproach in lot of projects that rely on external auth.

Usually you get all your information in a single query at login time and you store it in a list (or array, tupla, etc)  so you can access it later. the only drawback is when group membership changes while you're logged in, but that usually don't happen very often in a typical environment, so I don't think is critical.

**Comment by bugy** [comment]
Added ACL support (without LDAP groups yet):
- you can define "allowed_users" in a script configuration. It should be a list of users or groups. Groups should be prefixed by @ sign, e.g.:
`"allowed_users": ["127.0.0.1", "@developers", "buggygm@gmail.com"]`
- groups can be defined in a server configuration file (conf.json), under access -> groups (see example below)
- there is a default group @admin_users, which is taken from server configuration file for admin users
- groups can be defined recursively

Example of conf.json
```
{
"access": {
    "admin_users": ["userX"]
    "groups": {
        "dev": ["user1"], 
        "support": ["user2"],
        "tech-guys": ["@dev", "@support", "@admin_users", "another_user"]
    }
}
```

Going to add LDAP support in a couple of days. In this case user groups will be a union from LDAP and configuration file.

**Comment by bugy** [comment]
Added support for ldap groups. On user login, his/her groups will be fetched and stored locally (temp/ldap_groups.json) file.

For resolving user groups, base dn should/can be specified:
- conf.json file: auth -> groups_base_dn, example:
`"groups_base_dn": "dc=global"`
- if the configuration is missing, it will be resolved from username_pattern:
-- if the pattern is ...,dc=name1,dc=name2, then base dn would be all the dc (dc=name1,dc=name2)
-- if the patter is username@domain1.domain2, then base dn would be dc=domain1,dc=domain2

**Comment by muzzol** [comment]
can I suggest some log information about groups? for example something like:

```
2018-07-19 14:43:12,566 [script_server.LdapAuthorizer.INFO] Logging in user e10000
2018-07-19 14:43:12,982 [script_server.tornado_auth.INFO] Authenticated user e10000
2018-07-19 14:43:12,983 [script_server.tornado_auth.INFO] Groups for user e10000 (sysadmins, operators, samba-admin)
```

this makes a lot easier to debug membership problems.

**Comment by bugy** [comment]
Good idea, I'll add it.
For now you can check temp/ldap-groups.json file

**Comment by muzzol** [comment]
yeah, I know that.

great work by the way. I'm currently testing it and I love it.

 :)

**Comment by bugy** [comment]
Hi, I'm glad you likes it :)
Hopefully the configuration is not very confusing

**Comment by bugy** [comment]
While testing the feature on our AD setup, I've found out, that the solution didn't work in such setup, because user cn didn't match userPrincipalName. 
So I've improved the implementation and now user dn and uid are resolved before loading corresponding groups. This dn/uid resolve is `username_pattern` dependant and currently supports the following patterns:
1. ...$username...,dc=abc,dc=def: in this case it's treated as a correct user dn
2. $username@domain.com: the user will be searched by userPrincipalName match
3. domain\\$username: the user will be searched by sAMAccountName=$username

I also renamed config property from `groups_base_dn` to `base_dn`, because now it's used not only for groups. Since the feature is not yet released, I decided to go for this small backward incompatibility sin. 

@muzzol, I would greatly appreciate if you could check the latest version and say if it's still working for you.

**Comment by muzzol** [comment]
hey, sorry about answering late.

Real Life is keeping me busy.
I'll try to test this against regular LDAP and AD as soon as I can, probable next week.

happy holydays! 

https://i.imgur.com/jJ5l7iN.jpg

I'm the one on the right, btw :D

**Comment by bugy** [comment]
Hi @muzzol, no worries, there is no urge here, I believe everything should work :)

Have a good holidays!

**Comment by gsmolensky** [comment]
Hi guys i would like to ask you about , LDAP i am trying to set up but still have some mistakes , my conf.json looks : 

  "auth": {
    "type": "ldap",
    "url": "ldaps://1.2.3.4:636",
    "username_pattern": "$username@adam.sk",
    "version": 3,
    "base_dn": "dc=test,dc=ldap"
  },
  "access": {
        "allowed_users": ["*"],
        "admin_users": [ "adam1@adam.sk" ],
        "groups": {
                "all": ["@admin_users", "@dev", "@support", "alice"]
        },
        "trusted_ips": [ "0.0.0.0" ]
  },


And when i try to start launcher.py i get this error message : 

[root@blabla script-server]# ./launcher.py
Traceback (most recent call last):
  File "./launcher.py", line 11, in <module>
    main.main()
  File "src/main.py", line 55, in main
    server_config = server_conf.from_json(SERVER_CONF_PATH, TEMP_FOLDER)
  File "src/model/server_conf.py", line 105, in from_json
    config.authenticator = create_authenticator(auth_config, temp_folder)
  File "src/model/server_conf.py", line 141, in create_authenticator
    from auth.auth_ldap import LdapAuthenticator
  File "src/auth/auth_ldap.py", line 6, in <module>
    from ldap3 import Connection, SIMPLE
  File "/usr/lib/python3.4/site-packages/ldap3-2.5.1-py3.4.egg/ldap3/__init__.py", line 138, in <module>
  File "/usr/lib/python3.4/site-packages/ldap3-2.5.1-py3.4.egg/ldap3/core/connection.py", line 37, in <module>
  File "/usr/lib/python3.4/site-packages/ldap3-2.5.1-py3.4.egg/ldap3/extend/__init__.py", line 45, in <module>
  File "/usr/lib/python3.4/site-packages/ldap3-2.5.1-py3.4.egg/ldap3/extend/standard/whoAmI.py", line 27, in <module>
ImportError: cannot import name 'NoValue'

**Comment by bugy** [comment]
From a quick look, the config looks fine. It seems that the problem with ldap3 package itself.

Could it be the similar problem? https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=905757 
Could you also check please, if pyasn1 package is installed? E.g.:
```
yshepilov@yshepilov-pc:~$ pip3 search pyasn1
pyasn1 (0.4.4)          - ASN.1 types and codecs
  INSTALLED: 0.4.4 (latest)
```

**Comment by muzzol** [comment]
maybe you could try with a simple configuration first.

I'm using something as simple as this


```
{
  "auth": {
    "type": "ldap",
    "url": "ldap://ldap.example.net",
    "username_pattern": "uid=$username,ou=Users,dc=example.net,dc=global",
    "version": 3
  },
  "title": "Example Scripts"
}


```

and I can login with any LDAP user.

**Comment by gsmolensky** [comment]
Hi thanks for your help, i installed this package and then it works 
https://pypi.org/project/ldap3/
